USE `cmevents`;

ALTER TABLE `Conference` ADD COLUMN `CHAT` VARCHAR(255) NULL  AFTER `webCodec` , ADD COLUMN `START_TIME` DATETIME NOT NULL  AFTER `webCodec` , ADD COLUMN `STOP_TIME` DATETIME NOT NULL  AFTER `START_TIME` ;

UPDATE Conference, ConferenceTime
SET Conference.START_TIME=ConferenceTime.START_TIME, Conference.STOP_TIME=ConferenceTime.STOP_TIME
WHERE Conference.CONFERENCE_ID=ConferenceTime.CONFERENCE_ID;

ALTER TABLE `Session` ADD COLUMN `START` BIGINT(20) NOT NULL AFTER `CONFERENCE_ID` , ADD COLUMN `STOP` BIGINT(20) NOT NULL AFTER `START` ;

UPDATE Session, Conference
SET Session.START=(unix_timestamp(Session.START_TIME)-unix_timestamp(Conference.START_TIME))*1000, 
Session.STOP=(unix_timestamp(Session.STOP_TIME)-unix_timestamp(Conference.START_TIME))*1000
WHERE Conference.CONFERENCE_ID=Session.CONFERENCE_ID;

ALTER TABLE `Session` DROP COLUMN `START_TIME` , DROP COLUMN `STOP_TIME` , CHANGE COLUMN `START` `START_TIME` BIGINT(20) NOT NULL DEFAULT '0'  , CHANGE COLUMN `STOP` `STOP_TIME` BIGINT(20) NOT NULL DEFAULT '0';